### ISSUE TITLE
LICENSE ‽

### ISSUE THREAD

**Issue by shuvashish76** [bazsimarkus/EyeTool#1]
Since the source code is open, would you consider adding an open source license to it so that others can fork and improve/maintain the project ?

**Comment by bazsimarkus** [comment]
Hey @shuvashish76 ,

Good point, I've just added the MIT license in the root of the repository.
[https://github.com/bazsimarkus/EyeTool/commit/43c4cc430749f65a6747e45b74d2fb482c62222e](https://github.com/bazsimarkus/EyeTool/commit/43c4cc430749f65a6747e45b74d2fb482c62222e)
